spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/user_management_system?allowPublicKeyRetrieval=true&useSSL=false'
    username: 'postgres'
    password: 'root'
    driver-class-name: org.postgresql.Driver